(specifications->manifest (list
                            ;; base packages
                            "bash-minimal"
                            "glibc-locales"
                            "nss-certs"
                            ;; Common command line tools lest the container is too empty.
                            "coreutils"
                            "grep"
                            "which"
                            "wget"
                            "sed"
                            ;; Toolchain and common libraries for "install.packages"
                            "gcc-toolchain@11"
                            "gfortran-toolchain@11"
                            "gawk"
                            "tar"
                            "gzip"
                            "unzip"
                            "make"
                            "cmake"
                            "pkg-config"
                            "cairo"
                            "libxt"
                            "openssl"
                            "curl"
                            "zlib"
                            "tzdata"
                            "vim"
                            "file"
                            "readline"
                            ;; r stuff
                            "r"
                            "r-data-table"
                            "r-tidyverse"
                            "r-prism"
                            "r-terra"
                            "r-sf"
                            "r-sp"
                            "r-raster"
                            "r-rastervis"
                            "r-latticeextra"
                            "r-brms"
                            "r-jagsui"
                            "r-bayesplot"
                            "r-tidybayes"
                            "r-ggplot2"
                            "r-lubridate"
                            "r-loo"
                            "r-performance"
                            "r-bayesmix"
                            "r-rjags"
                            "r-r2jags"
                            "r-spdep"
                            "r-gstat"
                            "r-zoo"
                          ))
