(specifications->manifest (list
                            ;; base packages
                            ;;"bash-minimal"
                            "bash"
                            "bash-completion"
                            "glibc-locales"
                            "nss-certs"
                            ;; Common command line tools lest the container is too empty.
                            "coreutils"
                            "curl"
                            "grep"
                            "sed"
                            "wget"
                            "which"
                            ;; Toolchain and common libraries for "install.packages"
                            "cairo"
                            "cmake"
                            "gcc-toolchain@10"
                            "gfortran-toolchain"
                            "gawk"
                            "gzip"
                            "libxt"
                            "make"
                            "openssl"
                            "pkg-config"
                            "r"
                            "tar"
                            "tcl"
                            "unzip"
                            "zlib"
                            ;; common dependencies for r
                            "fontconfig"
                            "fribidi"
                            "harfbuzz"
                            "libxml2"
                            ;; r stuff
                            "r"
                            "r-biocversion"
                            "r-biocmanager"
                            "r-dplyr"
                            "r-devtools"
                            "r-here"
                            "r-jpeg"
                            "r-jsonlite"
                            "r-limpca"
                            "r-matrix"
                            "r-tidyverse"
                            "r-tidymodels"
                          ))
