(specifications->manifest (list
                            ;; base packages
                            ;;"bash-minimal"
                            "bash"
                            "bash-completion"
                            "glibc-locales"
                            "nss-certs"
                            ;; Common command line tools lest the container is too empty.
                            "coreutils"
                            "curl"
                            "grep"
                            "sed"
                            "wget"
                            "which"
                            ;; Toolchain and common libraries for "install.packages"
                            "cairo"
                            "cmake"
                            "gcc-toolchain@10"
                            "gfortran-toolchain"
                            "gawk"
                            "gzip"
                            "libxt"
                            "make"
                            "openssl"
                            "pkg-config"
                            "r"
                            "rstudio"
                            "rstudio-server"
                            "tar"
                            "tcl"
                            "unzip"
                            "zlib"
                            ;; common dependencies for r
                            "fontconfig"
                            "fribidi"
                            "harfbuzz"
                            "libxml2"
                            ;; r stuff
                            "r"
                            "r-dplyr"
                            "r-devtools"
			    "r-tidyverse"
                            "r-knitr"
			    "r-kableextra"
			    "r-data-table"
			    "r-duckdb"
			    "r-dbi"
			    "r-zoo"
			    "r-fixest"
			    "r-ggplot2"
			    "r-arrow"
			    "r-purrr"
                          ))
